<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(

            [
                'ISO' => 'AED',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'AFN',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'ALL',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'AMD',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'ANG',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'AOA',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'ARS',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'AUD',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'AWG',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'AZN',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ],
            [
                'ISO' => 'BAM',
                'modify_uid' => 0,
                'create_dt' => now(),
                'modify_dt' => now(),
            ]
            //TODO
                    
                    // 'BBD',
                    // 'BDT',
                    // 'BGN',
                    // 'BHD',
                    // 'BIF',
                    // 'BMD',
                    // 'BND',
                    // 'BOB',
                    // 'BRL',
                    // 'BSD',
                    // 'BTN',
                    // 'BWP',
                    // 'BYN',
                    // 'BYR',
                    // 'BZD',
                    // 'CAD',
                    // 'CDF',
                    // 'CHF',
                    // 'CLP',
                    // 'CNY',
                    // 'COP',
                    // 'CRC',
                    // 'CUC',
                    // 'CUP',
                    // 'CVE',
                    // 'CZK',
                    // 'DJF',
                    // 'DKK',
                    // 'DOP',
                    // 'DZD',
                    // 'EGP',
                    // 'ERN',
                    // 'ETB',
                    // 'EUR',
                    // 'FJD',
                    // 'FKP',
                    // 'GBP',
                    // 'GEL',
                    // 'GHS',
                    // 'GIP',
                    // 'GMD',
                    // 'GNF',
                    // 'GTQ',
                    // 'GYD',
                    // 'HKD',
                    // 'HNL',  
                    // 'HRK',
                    // 'HTG',
                    // 'HUF',
                    // 'IDR',
                    // 'ILS',
                    // 'INR',
                    // 'IQD',
                    // 'ISK',
                    // 'JMD',
                    // 'JOD',
                    // 'JPY',
                    // 'KES',
                    // 'KGS',
                    // 'KHR',
                    // 'KMF',
                    // 'KPW',
                    // 'KRW',
                    // 'KWD',
                    // 'KYD',
                    // 'KZT',
                    // 'LAK',
                    // 'LBP',
                    // 'LEK',
                    // 'LKR',
                    // 'LRD',
                    // 'LSL',
                    // 'LYD',
                    // 'MAD',
                    // 'MDL',
                    // 'MGA',
                    // 'MKD',
                    // 'MMK',
                    // 'MNT',
                    // 'MOP',
                    // 'MRU',
                    // 'MUR',
                    // 'MVR',
                    // 'MWK',
                    // 'MXN',
                    // 'MYR',
                    // 'MZN',
                    // 'NAD',
                    // 'NGN',
                    // 'NIO',
                    // 'NOK',
                    // 'NPR',
                    // 'NZD',
                    // 'OMR',
                    // 'PAB',
                    // 'PEN',
                    // 'PGK',
                    // 'PHP',
                    // 'PKR',
                    // 'PLN',
                    // 'PYG',
                    // 'QAR',
                    // 'RON',
                    // 'RSD',
                    // 'RWF',
                    // 'SAR',
                    // 'SBD',
                    // 'SCR',
                    // 'SDG',
                    // 'SEK',
                    // 'SGD',
                    // 'SLE',
                    // 'SOS',
                    // 'SRD',
                    // 'SSP',
                    // 'SYP',
                    // 'SZL',
                    // 'THB',
                    // 'TJS',
                    // 'TMT',
                    // 'TND',
                    // 'TOP',
                    // 'TRY',
                    // 'TTD',
                    // 'TWD',
                    // 'TZS',
                    // 'UAH',
                    // 'UGX',
                    // 'USD',
                    // 'UYU',
                    // 'UZS',
                    // 'VEF',
                    // 'VES',
                    // 'VND',
                    // 'VUV',
                    // 'WST',
                    // 'XAF',
                    // 'XCD',
                    // 'XOF',
                    // 'XPF',
                    // 'YER',
                    // 'ZAR',
                    // 'ZMW',
                    // 'ZWL'
        );
        
        DB::table('ts_api_currencies')->insert($data);
    }
}