# TPSN Backend Build

pipelines:

  branches:
    develop:
      - step:
          name: Deploy to testing server
          deployment: Test
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER_HOST
                PORT: $PORT
                COMMAND: "/var/www/html/backend-api/pipeline_script.sh"
                ENV_VARS: >-
                  TG_TOKEN=${TG_TOKEN}
                  TG_USER=${TG_USER}

  uat:
      - step:
          name: Deploy to testing server
          deployment: UAT-Test
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER_HOST
                PORT: $PORT
                COMMAND: "/var/www/html/backend-api/pipeline_script.sh"
                ENV_VARS: >-
                  TG_TOKEN=${TG_TOKEN}
                  TG_USER=${TG_USER}
