version: '3.8'
services:
  andrewayson-laravel-backend:
    image: takamata018/laravel7.4-fpm
    restart: unless-stopped
    container_name: andrewayson-laravel-backend
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
    ports:
      - ${APP_MACHINE_SECURE_HOST_PORT}:9000
    networks:
      - ${NETWORK}
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: andrewayson-laravel-backend-nginx
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
      - ${HOST_MACHINE_SECURE_HOST_PORT}:443
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_DIR}:/var/log/nginx
    depends_on:
      - andrewayson-laravel-backend
    networks:
      - ${NETWORK}

  # db:
  #   image: mysql
  #   container_name: andrewayson-laravel-backend-mysql
  #   restart: always
  #   command: --lower_case_table_names=2
  #   ports:
  #     - ${DATABASE_HOST_MACHINE_HOST_PORT}:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MY_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - ./containerization/andrewayson-laravel-be-db-data:/var/lib/mysql

  # install:
  #   extends:
  #     service: andrewayson-laravel-backend
  #   command: composer install
  # build:
  #   extends:
  #     service: andrewayson-laravel-backend
  #   command: bash -c "chmod -R 777 storage && php artisan key:generate"
  # migrate:
  #   extends:
  #     service: andrewayson-laravel-backend
  #   command: php artisan migrate

networks:
  andrewayson-laravel-backend:
    name: ${NETWORK}

# volumes:
#   andrewayson-laravel-be-db-data:
#     external: true