version: '3.9'

services:
  andrewayson-laravel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: andrewayson-laravel-backend
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
    ports:
      - "${APP_MACHINE_SECURE_HOST_PORT}:9000"
    networks:
      - andrewayson-laravel-backend
    env_file:  # Ensure environment variables are passed to the container
      - .env

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: andrewayson-laravel-backend-nginx
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_DIR}:/var/log/nginx
    depends_on:
      - andrewayson-laravel-backend
    networks:
      - andrewayson-laravel-backend
    env_file:  # Ensure environment variables are passed to the container
      - .env

  db:
    image: postgres
    container_name: andrewayson-laravel-backend-postgres
    restart: always
    ports:
      - "${DATABASE_HOST_MACHINE_HOST_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./containerization/andrewayson-laravel-be-db-data:/var/lib/postgresql/data
    networks:
      - andrewayson-laravel-backend

networks:
  andrewayson-laravel-backend:
    name: andrewayson-laravel-backend
