version: '3'
services:
  humite-backend:
    image: takamata018/laravel7.4-fpm
    restart: unless-stopped
    container_name: humite-backend
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
    ports:
      - "${APP_MACHINE_SECURE_HOST_PORT}:9000"
    networks:
      - ${NETWORK}
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: humite-backend-nginx
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_DIR}:/var/log/nginx
    depends_on:
      - humite-backend
    networks:
      - ${NETWORK}
  db:
    image: postgres:14-alpine
    container_name: humite-backend-postgresql
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=spribe

networks:
  humite-backend:
    name: ${NETWORK}

# volumes:
#   humite-be-db-data:
#     external: true